// swift-tools-version: 6.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "swift-leveldb",
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "swift-leveldb",
            targets: ["swift-leveldb"]
        ),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "CLevelDB",
            path: "Vendor/leveldb",
            exclude: [
                ".appveyor.yml",
                ".clang-format",
                ".gitignore",
                ".gitmodules",
                ".travis.yml",
                "AUTHORS",
                "CMakeLists.txt",
                "CONTRIBUTING.md",
                "LICENSE",
                "NEWS",
                "README.md",
                "TODO",
                "benchmarks",
                "cmake",
                "doc",
                "issues",
                "helpers/memenv/memenv_test.cc",
                "db/autocompact_test.cc",
                "db/c_test.c",
                "db/corruption_test.cc",
                "db/db_test.cc",
                "db/dbformat_test.cc",
                "db/fault_injection_test.cc",
                "db/filename_test.cc",
                "db/leveldbutil.cc",
                "db/log_test.cc",
                "db/recovery_test.cc",
                "db/skiplist_test.cc",
                "db/version_edit_test.cc",
                "db/version_set_test.cc",
                "db/write_batch_test.cc",
                "port/README.md",
                "port/port_config.h.in",
                "port/port_example.h",
                "table/filter_block_test.cc",
                "table/table_test.cc",
                "util/arena_test.cc",
                "util/bloom_test.cc",
                "util/cache_test.cc",
                "util/coding_test.cc",
                "util/crc32c_test.cc",
                "util/env_posix_test.cc",
                "util/env_posix_test_helper.h",
                "util/env_test.cc",
                "util/env_windows.cc",
                "util/env_windows_test.cc",
                "util/env_windows_test_helper.h",
                "util/hash_test.cc",
                "util/histogram.cc",
                "util/histogram.h",
                "util/logging_test.cc",
                "util/no_destructor_test.cc",
                "util/status_test.cc",
                "util/testutil.cc",
                "util/testutil.h",
                "util/windows_logger.h",
            ],
            sources: [
                "db/builder.cc",
                "db/c.cc",
                "db/db_impl.cc",
                "db/db_iter.cc",
                "db/dbformat.cc",
                "db/dumpfile.cc",
                "db/filename.cc",
                "db/log_reader.cc",
                "db/log_writer.cc",
                "db/memtable.cc",
                "db/repair.cc",
                "db/table_cache.cc",
                "db/version_edit.cc",
                "db/version_set.cc",
                "db/write_batch.cc",
                "helpers/memenv/memenv.cc",
                "table/block.cc",
                "table/block_builder.cc",
                "table/filter_block.cc",
                "table/format.cc",
                "table/iterator.cc",
                "table/merger.cc",
                "table/table.cc",
                "table/table_builder.cc",
                "table/two_level_iterator.cc",
                "util/arena.cc",
                "util/bloom.cc",
                "util/cache.cc",
                "util/coding.cc",
                "util/comparator.cc",
                "util/crc32c.cc",
                "util/env.cc",
                "util/env_posix.cc",
                "util/filter_policy.cc",
                "util/hash.cc",
                "util/logging.cc",
                "util/options.cc",
                "util/status.cc",
            ],
            publicHeadersPath: "include",
            cxxSettings: [
                .define("LEVELDB_PLATFORM_POSIX", to: "1"),
                .define("LEVELDB_COMPILE_LIBRARY"),
                .headerSearchPath("."),
            ]
        ),
        .target(
            name: "swift-leveldb",
            dependencies: ["CLevelDB"]
        ),
        .testTarget(
            name: "swift-leveldbTests",
            dependencies: ["swift-leveldb"]
        ),
    ],
    swiftLanguageModes: [.v6],
    cxxLanguageStandard: .cxx11
)
